CREATE TABLE Usuarios ( Codigo INT PRIMARY KEY IDENTITY(1,1),Dcentidad NVARCHAR(100), 
Rsoci NVARCHAR(100), Codcue NVARCHAR(50), Direccion NVARCHAR(200), Email NVARCHAR(100), Contacto NVARCHAR(50), Pw NVARCHAR(255),
Tipo NVARCHAR(50) );